/*Valores límite*/
#define MIN_VALOR_RESISTENCIA 100
#define MAX_VALOR_RESISTENCIA 5000000
#define MIN_VALOR_CAPACIDAD 1
#define MAX_VALOR_CAPACIDAD 10000
#define MIN_VALOR_FRECUENCIA 1
#define MAX_VALOR_FRECUENCIA 1000000

#define MAX_STR 1000
#define MAX_DIGITS 1
#define MAX_MSJ 100

/*opciones*/
#define CANTIDAD_OPCIONES_MAIN_MENU 3
#define CANTIDAD_OPCIONES_MENU_FREC 6
#define CANTIDAD_OPCIONES_MENU_FACTOR_CAL 2
#define MAX_DIG_OPC_FREQ_MENU 1
#define MAX_DIG_OPC_MAIN_MENU 1
#define MAX_DIG_OPC_FACTOR_MENU 1

/*Constantes*/
#define CTE_2PI 6.28318